apiVersion: v1
kind: Secret
metadata:
  name: glpi-secret
type: Opaque
data:
  MARIADB_HOST: "bWFyaWFkYi1nbHBpCg=="
  MARIADB_PORT: "MzMwNgo="
  MARIADB_DATABASE: "Z2xwaQo="
  MARIADB_USER: "Z2xwaQo="
  MARIADB_PASSWORD: "Z2xwaQo="
