apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels: 
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - image: fametec/glpi:9.5.6
        name: glpi
        env: 
        - name: GLPI_LANG
          value: "pt_BR"
        - name: MARIADB_HOST
          value: "mariadb-glpi"
        - name: MARIADB_PORT
          value: "3306"
        - name: MARIADB_DATABASE
          value: "glpi"
        - name: MARIADB_USER
          value: "glpi"
        - name: MARIADB_PASSWORD
          value: "glpi"
        - name: VERSION
          value: "9.5.6"
        - name: PLUGINS
          value: "all"
        ports:
        - containerPort: 80
          name: glpi
#        volumeMounts:
#        - name: files-glpi-persistent-storage
#          mountPath: /var/www/html/files
#        - name: plugins-glpi-persistent-storage
#          mountPath: /var/www/html/plugins
#      volumes:
#      - name: files-glpi-persistent-storage
#        persistentVolumeClaim:
#          claimName: files-glpi-pv-claim
#      - name: plugins-glpi-persistent-storage
#        persistentVolumeClaim:
#          claimName: plugins-glpi-pv-claim



